### ISSUE TITLE
ServiceCollection -> ServiceProvider

### ISSUE THREAD

**Issue by ahczbhht1989** [mineichen/minfac#1]
Does it possible only use ServiceCollection to get the services,doesn't use ServiceProvider。
I find the js inverify lib usage like this
```js
// Declare bindings
var container = new inversify.Container();
container.bind(TYPES.Ninja).to(Ninja);
container.bind(TYPES.Ninja).to(NinjaImpl);
container.bind(TYPES.Katana).to(Katana);
container.bind(TYPES.Shuriken).to(Shuriken);

// Resolve dependencies
var ninja = container.get(TYPES.Ninja);
```

**Comment by mineichen** [comment]
This is impossible by design. ServiceCollection::build() turns the collection into an immutable ServiceProvider which can be used to resolve services. If you want to add Services to an existing ServiceProvider, you can however define a new ServiceCollection and inherit all services with ServiceCollection::with_parent() and build a new ServiceProvider.

If this doesn't help, feel free to describe what you want to accomplish.
